/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Punchy API
 * Contract shared by the Punchy back office (admin and business managers) and the Punchy mobile
 * app (customers). Until the backend exists, the back office serves every operation below from an
 * in-memory mock (`src/mocks/`), so this document is the source of truth for both sides.
 *
 * Every authenticated call carries `Authorization: Bearer <token>`. The token carries the user's
 * role and, for a manager, the business the manager works for: `business/*` operations are always
 * scoped to that business, never to a business id taken from the path.
 *
 * Errors share one body, `ApiError`, whose `code` is stable and machine-readable.
 *
 * OpenAPI spec version: 0.1.0
 */
import {
  HttpClient
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  PasswordChange,
  ProfileUpdate,
  User
} from '../../model';

import { apiRequest } from '../../../../../../core/http/api-request';








@Injectable({ providedIn: 'root' })
export class AccountService {
  private readonly http = inject(HttpClient);
 getMe<TData = User>(

 ) {
      return apiRequest<TData>(
      {url: `/account/me`, method: 'GET'
    },
      this.http,
      );
    }
   updateMe<TData = User>(
    profileUpdate: ProfileUpdate,
 ) {
      return apiRequest<TData>(
      {url: `/account/me`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: profileUpdate
    },
      this.http,
      );
    }
   changePassword<TData = void>(
    passwordChange: PasswordChange,
 ) {
      return apiRequest<TData>(
      {url: `/account/password`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: passwordChange
    },
      this.http,
      );
    }
  };

export type GetMeClientResult = NonNullable<User>
export type UpdateMeClientResult = NonNullable<User>
export type ChangePasswordClientResult = NonNullable<void>
