/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Punchy API
 * Contract shared by the Punchy back office (admin and business managers) and the Punchy mobile
 * app (customers). Until the backend exists, the back office serves every operation below from an
 * in-memory mock (`src/mocks/`), so this document is the source of truth for both sides.
 *
 * Every authenticated call carries `Authorization: Bearer <token>`. The token carries the user's
 * role and, for a manager, the business the manager works for: `business/*` operations are always
 * scoped to that business, never to a business id taken from the path.
 *
 * Errors share one body, `ApiError`, whose `code` is stable and machine-readable.
 *
 * OpenAPI spec version: 0.1.0
 */

export interface ApiError {
  /**
     * One of `invalid_credentials`, `account_suspended`, `business_suspended`, `unauthorized`,
     * `forbidden`, `not_found`, `validation_error`, `wrong_password`, `email_taken`,
     * `card_number_taken`, `template_archived`, `card_full`, `card_not_active`,
     * `period_already_paid`, `reward_not_ready`, `customer_has_active_cards`, `logo_invalid`.
     */
  code: string;
  /** Developer-facing detail; never shown to users as is. */
  message?: string;
}
