/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Punchy API
 * Contract shared by the Punchy back office (admin and business managers) and the Punchy mobile
 * app (customers). Until the backend exists, the back office serves every operation below from an
 * in-memory mock (`src/mocks/`), so this document is the source of truth for both sides.
 *
 * Every authenticated call carries `Authorization: Bearer <token>`. The token carries the user's
 * role and, for a manager, the business the manager works for: `business/*` operations are always
 * scoped to that business, never to a business id taken from the path.
 *
 * Errors share one body, `ApiError`, whose `code` is stable and machine-readable.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { CardDesign } from './cardDesign';
import type { CardStyle } from './cardStyle';
import type { IssuerEmblem } from './issuerEmblem';
import type { StampStyle } from './stampStyle';

export interface Appearance {
  style: CardStyle;
  design: CardDesign;
  stampStyle: StampStyle;
  emblem?: IssuerEmblem;
}
