/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Punchy API
 * Contract shared by the Punchy back office (admin and business managers) and the Punchy mobile
 * app (customers). Until the backend exists, the back office serves every operation below from an
 * in-memory mock (`src/mocks/`), so this document is the source of truth for both sides.
 *
 * Every authenticated call carries `Authorization: Bearer <token>`. The token carries the user's
 * role and, for a manager, the business the manager works for: `business/*` operations are always
 * scoped to that business, never to a business id taken from the path.
 *
 * Errors share one body, `ApiError`, whose `code` is stable and machine-readable.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { AttentionItemReason } from './attentionItemReason';
import type { Card } from './card';

export interface AttentionItem {
  /**
     * `reward_ready`: a loyalty card is full. `expiring_soon`: `validUntil` within 14 days.
     * `month_unpaid`: a monthly card has no stamp for the current month. `balance_due`: an
     * entries card paid less than its price. `almost_used_up`: an entries card with at most
     * two boxes left.
     */
  reason: AttentionItemReason;
  card: Card;
}
