/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Punchy API
 * Contract shared by the Punchy back office (admin and business managers) and the Punchy mobile
 * app (customers). Until the backend exists, the back office serves every operation below from an
 * in-memory mock (`src/mocks/`), so this document is the source of truth for both sides.
 *
 * Every authenticated call carries `Authorization: Bearer <token>`. The token carries the user's
 * role and, for a manager, the business the manager works for: `business/*` operations are always
 * scoped to that business, never to a business id taken from the path.
 *
 * Errors share one body, `ApiError`, whose `code` is stable and machine-readable.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { CardProgram } from './cardProgram';

/**
 * What the business sells or hands out; every card is issued from one.
 */
export interface CardTemplate {
  id: string;
  /** Shown to staff only, e.g. "10 ingressi nuoto libero". */
  name: string;
  program: CardProgram;
  /**
     * @minimum 1
     * @maximum 60
     */
  totalSlots: number;
  /** `entries`: price of the package. `monthly`: the default monthly fee. Unused by `loyalty`. */
  priceCents?: number;
  /** `loyalty` only, in the customers' language. Required for `loyalty`. */
  reward?: string;
  /** Days from issue to `validUntil`; absent means the card does not expire. */
  validityDays?: number;
  /** Whether the holder's name is printed on the front. Loyalty cards are often anonymous. */
  printHolder: boolean;
  /** Archived templates issue no new cards; issued cards are unaffected. */
  archived: boolean;
  activeCardCount: number;
}
