/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Punchy API
 * Contract shared by the Punchy back office (admin and business managers) and the Punchy mobile
 * app (customers). Until the backend exists, the back office serves every operation below from an
 * in-memory mock (`src/mocks/`), so this document is the source of truth for both sides.
 *
 * Every authenticated call carries `Authorization: Bearer <token>`. The token carries the user's
 * role and, for a manager, the business the manager works for: `business/*` operations are always
 * scoped to that business, never to a business id taken from the path.
 *
 * Errors share one body, `ApiError`, whose `code` is stable and machine-readable.
 *
 * OpenAPI spec version: 0.1.0
 */
import type { CardCustomer } from './cardCustomer';
import type { CardProgram } from './cardProgram';
import type { CardStatus } from './cardStatus';
import type { Payment } from './payment';
import type { Stamp } from './stamp';

export interface Card {
  id: string;
  /** Unique within the business. Assigned in sequence unless given, so paper cards keep their number. */
  number: string;
  templateId: string;
  templateName: string;
  program: CardProgram;
  /** Copied from the template at issue. */
  totalSlots: number;
  /** Copied from the template at issue. */
  priceCents?: number;
  reward?: string;
  printHolder: boolean;
  validUntil?: string;
  customer: CardCustomer;
  status: CardStatus;
  /** A `loyalty` card whose boxes are all stamped and whose reward is not yet redeemed. */
  rewardReady: boolean;
  issuedAt: string;
  lastStampAt?: string;
  redeemedAt?: string;
  /** Oldest first. */
  stamps: Stamp[];
  /** Oldest first. */
  payments: Payment[];
  /** Sum of `payments`. */
  paidCents: number;
}
