/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Punchy API
 * Contract shared by the Punchy back office (admin and business managers) and the Punchy mobile
 * app (customers). Until the backend exists, the back office serves every operation below from an
 * in-memory mock (`src/mocks/`), so this document is the source of truth for both sides.
 *
 * Every authenticated call carries `Authorization: Bearer <token>`. The token carries the user's
 * role and, for a manager, the business the manager works for: `business/*` operations are always
 * scoped to that business, never to a business id taken from the path.
 *
 * Errors share one body, `ApiError`, whose `code` is stable and machine-readable.
 *
 * OpenAPI spec version: 0.1.0
 */

export interface Customer {
  id: string;
  firstName: string;
  lastName: string;
  /** The address the customer signs in to the app with. Without it the cards exist only in the back office. */
  email?: string;
  phone?: string;
  birthDate?: string;
  notes?: string;
  createdAt: string;
  activeCardCount: number;
  lastVisitAt?: string;
}
