/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Punchy API
 * Contract shared by the Punchy back office (admin and business managers) and the Punchy mobile
 * app (customers). Until the backend exists, the back office serves every operation below from an
 * in-memory mock (`src/mocks/`), so this document is the source of truth for both sides.
 *
 * Every authenticated call carries `Authorization: Bearer <token>`. The token carries the user's
 * role and, for a manager, the business the manager works for: `business/*` operations are always
 * scoped to that business, never to a business id taken from the path.
 *
 * Errors share one body, `ApiError`, whose `code` is stable and machine-readable.
 *
 * OpenAPI spec version: 0.1.0
 */
import {
  HttpClient
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  AdminOverview,
  Business,
  BusinessInput,
  BusinessPage,
  ListBusinessesParams,
  ListManagersParams,
  Manager,
  ManagerCreate,
  ManagerPage,
  ManagerUpdate,
  PasswordReset,
  StatusChange
} from '../../model';

import { apiRequest } from '../../../../../../core/http/api-request';








@Injectable({ providedIn: 'root' })
export class AdminService {
  private readonly http = inject(HttpClient);
 getAdminOverview<TData = AdminOverview>(

 ) {
      return apiRequest<TData>(
      {url: `/admin/overview`, method: 'GET'
    },
      this.http,
      );
    }
   listBusinesses<TData = BusinessPage>(
    params?: ListBusinessesParams,
 ) {
      return apiRequest<TData>(
      {url: `/admin/businesses`, method: 'GET',
        params: (() => {

  const filteredParams: Record<string, string | number | boolean | Array<string | number | boolean>> = {};
  for (const [key, value] of Object.entries(params ?? {})) {
    if (Array.isArray(value)) {
      const filtered = value
        .filter(
          (item) =>
            item != null &&
            (typeof item === 'string' ||
              typeof item === 'number' ||
              typeof item === 'boolean' ||
              ((item as unknown) instanceof Date &&
                !Number.isNaN((item as unknown as Date).getTime()))),
        )
        .map((item) =>
          (item as unknown) instanceof Date
            ? (item as unknown as Date).toISOString()
            : item,
        ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (
      (value as unknown) instanceof Date &&
      !Number.isNaN((value as unknown as Date).getTime())
    ) {
      // useDates produces Date query params; serialize to ISO so they reach
      // the wire instead of being dropped by the primitive check below. See #3856.
      filteredParams[key] = (value as unknown as Date).toISOString();
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
})()
    },
      this.http,
      );
    }
   createBusiness<TData = Business>(
    businessInput: BusinessInput,
 ) {
      return apiRequest<TData>(
      {url: `/admin/businesses`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: businessInput
    },
      this.http,
      );
    }
   getBusiness<TData = Business>(
    businessId: string,
 ) {
      return apiRequest<TData>(
      {url: `/admin/businesses/${businessId}`, method: 'GET'
    },
      this.http,
      );
    }
   updateBusiness<TData = Business>(
    businessId: string,
    businessInput: BusinessInput,
 ) {
      return apiRequest<TData>(
      {url: `/admin/businesses/${businessId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: businessInput
    },
      this.http,
      );
    }
  /**
 * Suspending a business signs out and blocks every one of its managers, whatever their own
 * status; reactivating it restores each manager to their own status.
 */
 setBusinessStatus<TData = Business>(
    businessId: string,
    statusChange: StatusChange,
 ) {
      return apiRequest<TData>(
      {url: `/admin/businesses/${businessId}/status`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: statusChange
    },
      this.http,
      );
    }
   listManagers<TData = ManagerPage>(
    params?: ListManagersParams,
 ) {
      return apiRequest<TData>(
      {url: `/admin/managers`, method: 'GET',
        params: (() => {

  const filteredParams: Record<string, string | number | boolean | Array<string | number | boolean>> = {};
  for (const [key, value] of Object.entries(params ?? {})) {
    if (Array.isArray(value)) {
      const filtered = value
        .filter(
          (item) =>
            item != null &&
            (typeof item === 'string' ||
              typeof item === 'number' ||
              typeof item === 'boolean' ||
              ((item as unknown) instanceof Date &&
                !Number.isNaN((item as unknown as Date).getTime()))),
        )
        .map((item) =>
          (item as unknown) instanceof Date
            ? (item as unknown as Date).toISOString()
            : item,
        ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (
      (value as unknown) instanceof Date &&
      !Number.isNaN((value as unknown as Date).getTime())
    ) {
      // useDates produces Date query params; serialize to ISO so they reach
      // the wire instead of being dropped by the primitive check below. See #3856.
      filteredParams[key] = (value as unknown as Date).toISOString();
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
})()
    },
      this.http,
      );
    }
   createManager<TData = Manager>(
    managerCreate: ManagerCreate,
 ) {
      return apiRequest<TData>(
      {url: `/admin/managers`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: managerCreate
    },
      this.http,
      );
    }
   updateManager<TData = Manager>(
    managerId: string,
    managerUpdate: ManagerUpdate,
 ) {
      return apiRequest<TData>(
      {url: `/admin/managers/${managerId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: managerUpdate
    },
      this.http,
      );
    }
   setManagerStatus<TData = Manager>(
    managerId: string,
    statusChange: StatusChange,
 ) {
      return apiRequest<TData>(
      {url: `/admin/managers/${managerId}/status`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: statusChange
    },
      this.http,
      );
    }
   resetManagerPassword<TData = void>(
    managerId: string,
    passwordReset: PasswordReset,
 ) {
      return apiRequest<TData>(
      {url: `/admin/managers/${managerId}/password`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: passwordReset
    },
      this.http,
      );
    }
  };

export type GetAdminOverviewClientResult = NonNullable<AdminOverview>
export type ListBusinessesClientResult = NonNullable<BusinessPage>
export type CreateBusinessClientResult = NonNullable<Business>
export type GetBusinessClientResult = NonNullable<Business>
export type UpdateBusinessClientResult = NonNullable<Business>
export type SetBusinessStatusClientResult = NonNullable<Business>
export type ListManagersClientResult = NonNullable<ManagerPage>
export type CreateManagerClientResult = NonNullable<Manager>
export type UpdateManagerClientResult = NonNullable<Manager>
export type SetManagerStatusClientResult = NonNullable<Manager>
export type ResetManagerPasswordClientResult = NonNullable<void>
