/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Punchy API
 * Contract shared by the Punchy back office (admin and business managers) and the Punchy mobile
 * app (customers). Until the backend exists, the back office serves every operation below from an
 * in-memory mock (`src/mocks/`), so this document is the source of truth for both sides.
 *
 * Every authenticated call carries `Authorization: Bearer <token>`. The token carries the user's
 * role and, for a manager, the business the manager works for: `business/*` operations are always
 * scoped to that business, never to a business id taken from the path.
 *
 * Errors share one body, `ApiError`, whose `code` is stable and machine-readable.
 *
 * OpenAPI spec version: 0.1.0
 */
import {
  HttpClient
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import type {
  Business,
  BusinessOverview,
  BusinessProfileUpdate,
  Card,
  CardIssue,
  CardPage,
  CardTemplate,
  CardTemplateInput,
  CardTemplateUpdate,
  CardUpdate,
  Customer,
  CustomerInput,
  CustomerPage,
  ListCardsParams,
  ListCustomersParams,
  ListTemplatesParams,
  PaymentInput,
  RedeemRequest,
  RedeemResponse,
  StampInput,
  UploadMyBusinessLogoBody
} from '../../model';

import { apiRequest } from '../../../../../../core/http/api-request';








@Injectable({ providedIn: 'root' })
export class BusinessService {
  private readonly http = inject(HttpClient);
 getMyBusiness<TData = Business>(

 ) {
      return apiRequest<TData>(
      {url: `/business`, method: 'GET'
    },
      this.http,
      );
    }
  /**
 * A manager edits the business's public details and card appearance; name and VAT number stay with the admin.
 */
 updateMyBusiness<TData = Business>(
    businessProfileUpdate: BusinessProfileUpdate,
 ) {
      return apiRequest<TData>(
      {url: `/business`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: businessProfileUpdate
    },
      this.http,
      );
    }
   uploadMyBusinessLogo<TData = Business>(
    uploadMyBusinessLogoBody: UploadMyBusinessLogoBody,
 ) {const formData = new FormData();
formData.append(`file`, uploadMyBusinessLogoBody.file);

      return apiRequest<TData>(
      {url: `/business/logo`, method: 'PUT',
       data: formData
    },
      this.http,
      );
    }
   deleteMyBusinessLogo<TData = Business>(

 ) {
      return apiRequest<TData>(
      {url: `/business/logo`, method: 'DELETE'
    },
      this.http,
      );
    }
   getBusinessOverview<TData = BusinessOverview>(

 ) {
      return apiRequest<TData>(
      {url: `/business/overview`, method: 'GET'
    },
      this.http,
      );
    }
   listTemplates<TData = CardTemplate[]>(
    params?: ListTemplatesParams,
 ) {
      return apiRequest<TData>(
      {url: `/business/templates`, method: 'GET',
        params: (() => {

  const filteredParams: Record<string, string | number | boolean | Array<string | number | boolean>> = {};
  for (const [key, value] of Object.entries(params ?? {})) {
    if (Array.isArray(value)) {
      const filtered = value
        .filter(
          (item) =>
            item != null &&
            (typeof item === 'string' ||
              typeof item === 'number' ||
              typeof item === 'boolean' ||
              ((item as unknown) instanceof Date &&
                !Number.isNaN((item as unknown as Date).getTime()))),
        )
        .map((item) =>
          (item as unknown) instanceof Date
            ? (item as unknown as Date).toISOString()
            : item,
        ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (
      (value as unknown) instanceof Date &&
      !Number.isNaN((value as unknown as Date).getTime())
    ) {
      // useDates produces Date query params; serialize to ISO so they reach
      // the wire instead of being dropped by the primitive check below. See #3856.
      filteredParams[key] = (value as unknown as Date).toISOString();
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
})()
    },
      this.http,
      );
    }
   createTemplate<TData = CardTemplate>(
    cardTemplateInput: CardTemplateInput,
 ) {
      return apiRequest<TData>(
      {url: `/business/templates`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: cardTemplateInput
    },
      this.http,
      );
    }
  /**
 * Changes apply to cards issued afterwards; issued cards keep the terms they were sold with.
 */
 updateTemplate<TData = CardTemplate>(
    templateId: string,
    cardTemplateUpdate: CardTemplateUpdate,
 ) {
      return apiRequest<TData>(
      {url: `/business/templates/${templateId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: cardTemplateUpdate
    },
      this.http,
      );
    }
   listCustomers<TData = CustomerPage>(
    params?: ListCustomersParams,
 ) {
      return apiRequest<TData>(
      {url: `/business/customers`, method: 'GET',
        params: (() => {

  const filteredParams: Record<string, string | number | boolean | Array<string | number | boolean>> = {};
  for (const [key, value] of Object.entries(params ?? {})) {
    if (Array.isArray(value)) {
      const filtered = value
        .filter(
          (item) =>
            item != null &&
            (typeof item === 'string' ||
              typeof item === 'number' ||
              typeof item === 'boolean' ||
              ((item as unknown) instanceof Date &&
                !Number.isNaN((item as unknown as Date).getTime()))),
        )
        .map((item) =>
          (item as unknown) instanceof Date
            ? (item as unknown as Date).toISOString()
            : item,
        ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (
      (value as unknown) instanceof Date &&
      !Number.isNaN((value as unknown as Date).getTime())
    ) {
      // useDates produces Date query params; serialize to ISO so they reach
      // the wire instead of being dropped by the primitive check below. See #3856.
      filteredParams[key] = (value as unknown as Date).toISOString();
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
})()
    },
      this.http,
      );
    }
   createCustomer<TData = Customer>(
    customerInput: CustomerInput,
 ) {
      return apiRequest<TData>(
      {url: `/business/customers`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: customerInput
    },
      this.http,
      );
    }
   getCustomer<TData = Customer>(
    customerId: string,
 ) {
      return apiRequest<TData>(
      {url: `/business/customers/${customerId}`, method: 'GET'
    },
      this.http,
      );
    }
   updateCustomer<TData = Customer>(
    customerId: string,
    customerInput: CustomerInput,
 ) {
      return apiRequest<TData>(
      {url: `/business/customers/${customerId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: customerInput
    },
      this.http,
      );
    }
   deleteCustomer<TData = void>(
    customerId: string,
 ) {
      return apiRequest<TData>(
      {url: `/business/customers/${customerId}`, method: 'DELETE'
    },
      this.http,
      );
    }
   listCards<TData = CardPage>(
    params?: ListCardsParams,
 ) {
      return apiRequest<TData>(
      {url: `/business/cards`, method: 'GET',
        params: (() => {

  const filteredParams: Record<string, string | number | boolean | Array<string | number | boolean>> = {};
  for (const [key, value] of Object.entries(params ?? {})) {
    if (Array.isArray(value)) {
      const filtered = value
        .filter(
          (item) =>
            item != null &&
            (typeof item === 'string' ||
              typeof item === 'number' ||
              typeof item === 'boolean' ||
              ((item as unknown) instanceof Date &&
                !Number.isNaN((item as unknown as Date).getTime()))),
        )
        .map((item) =>
          (item as unknown) instanceof Date
            ? (item as unknown as Date).toISOString()
            : item,
        ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (
      (value as unknown) instanceof Date &&
      !Number.isNaN((value as unknown as Date).getTime())
    ) {
      // useDates produces Date query params; serialize to ISO so they reach
      // the wire instead of being dropped by the primitive check below. See #3856.
      filteredParams[key] = (value as unknown as Date).toISOString();
    } else if (
      value != null &&
      (typeof value === 'string' ||
        typeof value === 'number' ||
        typeof value === 'boolean')
    ) {
      filteredParams[key] = value;
    }
  }
  return filteredParams;
})()
    },
      this.http,
      );
    }
   issueCard<TData = Card>(
    cardIssue: CardIssue,
 ) {
      return apiRequest<TData>(
      {url: `/business/cards`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: cardIssue
    },
      this.http,
      );
    }
   getCard<TData = Card>(
    cardId: string,
 ) {
      return apiRequest<TData>(
      {url: `/business/cards/${cardId}`, method: 'GET'
    },
      this.http,
      );
    }
   updateCard<TData = Card>(
    cardId: string,
    cardUpdate: CardUpdate,
 ) {
      return apiRequest<TData>(
      {url: `/business/cards/${cardId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: cardUpdate
    },
      this.http,
      );
    }
   cancelCard<TData = Card>(
    cardId: string,
 ) {
      return apiRequest<TData>(
      {url: `/business/cards/${cardId}/cancel`, method: 'POST'
    },
      this.http,
      );
    }
  /**
 * Validates one box: an entry, a monthly fee or a purchase. The operator's initials come from
 * the signed-in manager. For a `monthly` card `period` is required and, when `payment` is
 * given, the payment is recorded together with the stamp.
 */
 addStamp<TData = Card>(
    cardId: string,
    stampInput: StampInput,
 ) {
      return apiRequest<TData>(
      {url: `/business/cards/${cardId}/stamps`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: stampInput
    },
      this.http,
      );
    }
  /**
 * Undoes a stamp put by mistake, together with the payment recorded with it.
 */
 deleteStamp<TData = Card>(
    cardId: string,
    stampId: string,
 ) {
      return apiRequest<TData>(
      {url: `/business/cards/${cardId}/stamps/${stampId}`, method: 'DELETE'
    },
      this.http,
      );
    }
  /**
 * Records a payment that stamps nothing, such as the price of an entries package or a partial payment.
 */
 addPayment<TData = Card>(
    cardId: string,
    paymentInput: PaymentInput,
 ) {
      return apiRequest<TData>(
      {url: `/business/cards/${cardId}/payments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: paymentInput
    },
      this.http,
      );
    }
   deletePayment<TData = Card>(
    cardId: string,
    paymentId: string,
 ) {
      return apiRequest<TData>(
      {url: `/business/cards/${cardId}/payments/${paymentId}`, method: 'DELETE'
    },
      this.http,
      );
    }
  /**
 * Hands out the reward of a full `loyalty` card. The card becomes `completed`; with `renew` a fresh card on the same template is issued to the same customer.
 */
 redeemReward<TData = RedeemResponse>(
    cardId: string,
    redeemRequest: RedeemRequest,
 ) {
      return apiRequest<TData>(
      {url: `/business/cards/${cardId}/redeem`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: redeemRequest
    },
      this.http,
      );
    }
  };

export type GetMyBusinessClientResult = NonNullable<Business>
export type UpdateMyBusinessClientResult = NonNullable<Business>
export type UploadMyBusinessLogoClientResult = NonNullable<Business>
export type DeleteMyBusinessLogoClientResult = NonNullable<Business>
export type GetBusinessOverviewClientResult = NonNullable<BusinessOverview>
export type ListTemplatesClientResult = NonNullable<CardTemplate[]>
export type CreateTemplateClientResult = NonNullable<CardTemplate>
export type UpdateTemplateClientResult = NonNullable<CardTemplate>
export type ListCustomersClientResult = NonNullable<CustomerPage>
export type CreateCustomerClientResult = NonNullable<Customer>
export type GetCustomerClientResult = NonNullable<Customer>
export type UpdateCustomerClientResult = NonNullable<Customer>
export type DeleteCustomerClientResult = NonNullable<void>
export type ListCardsClientResult = NonNullable<CardPage>
export type IssueCardClientResult = NonNullable<Card>
export type GetCardClientResult = NonNullable<Card>
export type UpdateCardClientResult = NonNullable<Card>
export type CancelCardClientResult = NonNullable<Card>
export type AddStampClientResult = NonNullable<Card>
export type DeleteStampClientResult = NonNullable<Card>
export type AddPaymentClientResult = NonNullable<Card>
export type DeletePaymentClientResult = NonNullable<Card>
export type RedeemRewardClientResult = NonNullable<RedeemResponse>
